//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelReceiptPaymentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelReceiptPaymentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.Core.Properties.ExcelReceiptPaymentResource", typeof(ExcelReceiptPaymentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string ExcelColumnDC {
            get {
                return ResourceManager.GetString("ExcelColumnDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        internal static string ExcelColumnDG {
            get {
                return ResourceManager.GetString("ExcelColumnDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        internal static string ExcelColumnDT {
            get {
                return ResourceManager.GetString("ExcelColumnDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do thu/ chi.
        /// </summary>
        internal static string ExcelColumnLD {
            get {
                return ResourceManager.GetString("ExcelColumnLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán.
        /// </summary>
        internal static string ExcelColumnNHT {
            get {
                return ResourceManager.GetString("ExcelColumnNHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ.
        /// </summary>
        internal static string ExcelColumnSCT {
            get {
                return ResourceManager.GetString("ExcelColumnSCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        internal static string ExcelColumnST {
            get {
                return ResourceManager.GetString("ExcelColumnST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string ExcelColumnSTT {
            get {
                return ResourceManager.GetString("ExcelColumnSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        internal static string ExcelColumSUM {
            get {
                return ResourceManager.GetString("ExcelColumSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string ExcelColumTNV {
            get {
                return ResourceManager.GetString("ExcelColumTNV", resourceCulture);
            }
        }
    }
}
